### ISSUE TITLE
Design for use as a Python package

### ISSUE THREAD

**Issue by scossuhuit** [zimeon/ocfl-py#118]
The ability to use ocfl.py as a Python package in a larger application rather than a command-line script would be immensely useful. 

This is in some way already possible (obviously, because it IS a Python package), however the overall approach is biased toward CLI usage (e.g. `Store.list()` and `Object.show()` print human-readable representations rather than returning Python objects). 

API documentation and usage examples within a Python shell or program would be very useful as well.

**Comment by zimeon** [comment]
As of current working version (https://github.com/zimeon/ocfl-py/commit/a60e22d9ba3c3a0bb7ab4400883cb2000452b1db), all human readable output has been moved into the command line scripts or the specific helpers in `ocfl/command_line_utils.py`, thus cleaning up the code in `ocfl.StorageRoot` (formerly `ocfl.Store`) and `ocfl.Object`.

For example, `ocfl.StorageRoot` has generators `list_objects()` and `object_paths()` rather than a `list()` method with terminal/human output.

Also, I'm working on a pared down API defined by `ocfl/__init__.py` being somewhat selective on its imports and greater use of private (ie. starting with underscore) methods for code that shouldn't be more broadly user. And there are a growing number of code usage examples in the pydoc comments.

Closing this broad ticket but happy to consider specific suggestions.
